clc;
clear all;
close all;
am=2; ac=10;
fm=10; fc=50; fs=500;
t=0:1/fs:1;
m_t=am*cos(2*pi*fm*t);
c_t=ac*cos(2*pi*fc*t);
fdev=25;
b=fdev/fm;
k_t=b*sin(2*pi*fm*t);
s_t=ac*cos(2*pi*fc*t+k_t);
m_new=fmdemod(s_t,fc,fs,fdev);
subplot(4,1,1); plot(t,m_t,'linewidth',1.2,'color',[0 0.5 0]);
xlabel('time(sec)');
ylabel('amplitude in volts(V)');
title('MODULATING SIGNAL');
subplot(4,1,2); plot(t,c_t,'color','r','linewidth',1.1);
xlabel('time(sec)');
% ylabel('amplitude in volts(V)');
title('CARRIER SIGNAL');
subplot(4,1,3); plot(t,s_t,'color','m','linewidth',1.2);
xlabel('time(sec)');
% ylabel('amplitude in volts(V)');
title('FREQUENCY MODULATED SIGNAL');
subplot(4,1,4);plot(t,m_new);
xlabel('time(sec)');
% ylabel('amplitude in volts(V)');
title('DEMODULATED SIGNAL');